name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build MT2Config.slnx -c Release

      - uses: actions/upload-artifact@v7
        with:
          name: config
          path: MT2Config/bin/Release/config.exe
